fix some bugs
inspect-js/object-inspect pull request #42
Opened 2022-11-22 10:06 UTC by idanran

feat: add type
fix: esbuild prompt "Could not resolve 'util'" (#41)
chore: upgrade dep

2022-11-22 10:06 UTC, idanran commented
@ljharb PTAL

2022-11-22 23:26 UTC, ljharb requested changes

2022-11-22 23:26 UTC, ljharb commented on index.d.ts
> +    quoteStyle?: 'single' | 'double'
Types don’t belong in the package; they should only be in DefinitelyTyped.

2022-11-22 23:26 UTC, ljharb commented on index.js
> -var utilInspect = require('./util.inspect');
This is incorrect; the util module is always present, and the browser field handles that for working bundlers.

2022-11-22 23:26 UTC, ljharb commented on package.json
> +  "typings": "index.d.ts",
Please remove this.

2022-11-23 00:56 UTC, idanran commented
Thanks for the review. I agree with your thoughts. This PR should be closed.

2022-11-23 00:56 UTC, closed without merging